import type { Metadata, Viewport } from "next"; // Viewport 타입 추가
import localFont from "next/font/local";
import "./globals.css";
import ClientLayout from "./ClientLayout";
import { UserProvider } from "./context/UserContext";
import { NotificationProvider } from "./context/NotificationContext";
import { ToastProvider } from "./common/ToastProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// 1. Metadata에서 viewport 분리 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 2. Viewport 설정 수정
export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false, // 사용자가 임의로 확대/축소하는 것을 막아 앱처럼 보이게 함
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      {/* 3. antialiased 뒤에 bg-gray-50 등을 추가해 배경색을 잡으면 요소가 덜 커 보입니다 */}
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
        <UserProvider>
          <NotificationProvider>
            <ToastProvider>
              {/* 실제 컨텐츠는 ClientLayout에서 중앙 정렬 및 폭 제한을 수행하게 됩니다 */}
              <ClientLayout>{children}</ClientLayout>
            </ToastProvider>
          </NotificationProvider>
        </UserProvider>
      </body>
    </html>
  );
}